version: '3'

services:
  api:
    build: .
    image: trybe-course
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=db
      - DB_HOST=database
    depends_on: 
      - db
    command: dev
    volumes:
      - .:/app
    networks:
      - app-network
  
  db:
    image: mysql:8.0.32
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge